config/routes.rb
Rails.application.routes.draw do

  get 'settings/index'

  match '/signup',                to: 'users#new',            via: 'get'
  match '/signin',                to: 'sessions#new',         via: 'get'
  match '/signout',               to: 'sessions#destroy',     via: 'delete'

  match '/help',                  to: 'static_pages#help',    via: 'get'

  match '/users',                 to: 'users#index',          via: 'get'
  match '/about',                 to: 'static_pages#about',   via: 'get'

  match '/friends',               to: 'friendships#index',    via: 'get'
  match '/add_friend',            to: 'friendships#create',   via: 'get'
  match '/unfriend',              to: 'friendships#destroy',  via: 'delete'

   root 'static_pages#index'

  resources :users do
    member do
      patch :update_name
      patch :update_userinfo
    end
    resources :posts
    resources :conversations do
      resources :messages
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { self.email = email.downcase }
  before_create :create_remember_token

  has_many :friendships
  has_many :friends, :through => :friendships

  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  has_many :posts, :class_name => "Post", :foreign_key => "user_id"
  has_many :records, :class_name => "Post", :foreign_key => "author_id"

  has_many :conversations, :foreign_key => :sender_id

  # Country table is populated from seeds.rb, Cities table is populated by users
  belongs_to :gender
  belongs_to :relationship
  belongs_to :country
  belongs_to :city

  accepts_nested_attributes_for :city


  validates :name, presence: true, length: { maximum: 25 }
  validates :lastname, presence: true, length: { maximum:  25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }

  has_secure_password

  validates :password, length: { minimum: 6 }

  has_attached_file :avatar,
                    styles: { :small => ["160x160#", :png],
                              :medium => ["214x214>", :png],
                              :original => ["600x450>", :png]},
                    :default_url => "/assets/images/default_:style.png",
                    :dependent => :destroy

  validates_attachment_file_name :avatar,
                                 :matches => [/png\z/, /jpg\z/, /jpeg\z/]




  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end


  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new(:gender_id => 1)
  end

  def create
    @user = User.new(user_params)
    if @user.save

      #define_username(params[:user][:username_attributes][:name])
      #define_userlastname(params[:user][:userlastname_attributes][:lastname])
      define_gender(params[:user][:gender][:gender_id])

      #defines default values for fields had values and appeared in the edit screen
      @user.country = Country.first!
      @user.city = City.first!
      @user.relationship = Relationship.first!

      sign_in @user

      flash[:success] = "Welcome to our family! Please fill in your data below."
      redirect_to edit_user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.paginate(:page => params[:page], :per_page => 6)
  end

  def edit
    @user = User.find(params[:id])
  end

  #not used
  def update_name
    @user = User.find(params[:id])
    if @user.update_attribute(:name, params[:user][:name])
      #flash[:success] = "name updated"
      redirect_to @user
    else
      flash[:danger] = "not success"
      render 'edit'
    end
  end

  def update_userinfo
    @user = User.find(params[:id])
    @user.update_attributes(user_params)


    @user.relationship_id = params[:user][:relationship_id]
    @user.country = Country.find_by(:id => params[:user][:country_id])
    #@user.birthdate = params[:user][:birthdate
    @user.birthdate = Date.new(params[:user]["birthdate(1i)"].to_i,params[:user]["birthdate(2i)"].to_i,params[:user]["birthdate(3i)"].to_i)



    #define_username(params[:user][:username_attributes][:name])
    #define_userlastname(params[:user][:userlastname_attributes][:lastname])
    define_gender(params[:user][:gender_id])
    define_city(params[:user][:city_attributes][:cityname], params[:user][:country_id])


    render 'edit'

  end

  def post

  end



  private

    def user_params
      params.require(:user).permit(:name, :lastname, :gender_id, :email, :avatar, :password, :password_confirmation)
    end

    def define_username(name)
      @user.username_id = 1
      @username = Username.find_by(:name => name)
      if !@username.nil?
        @user.username = @username
      else
        @newname = Username.new(:name => name)
        @newname.save
        @user.username = @newname
      end
    end

    def define_userlastname(lastname)
      @user.userlastname_id = 1
      @userlastname = Userlastname.find_by(:lastname => lastname)
      if !@userlastname.nil?
        @user.userlastname = @userlastname
      else
        @newlastname = Userlastname.new(:lastname => lastname)
        @newlastname.save
        @user.userlastname = @newlastname
      end
    end

    def define_gender(gender_id)
      @user.gender_id = 1
      @user.update_attribute(:gender_id, gender_id)
      @user.save
    end


    def define_city(city, country_id)
      @user.city_id = 1
      @city = City.find_by(:cityname => city)
      if !@city.nil?
       @user.update_attribute(:city_id, @city.id)
      else
        @newcity = City.new(:cityname => city, :country_id => country_id)
        @newcity.save
        @user.update_attribute(:city_id, @newcity.id)
      end
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>

<div class="tabbable" id="tabs-738459" xmlns="http://www.w3.org/1999/html">
  <ul class="nav nav-tabs">
    <li class="active">
      <a href="#common" data-toggle="tab">Personal info</a>
    </li>
    <li>
      <a href="#languages" data-toggle="tab">Languages</a>
    </li>
    <li>
      <a href="#interests" data-toggle="tab">Interests</a>
    </li>
    <li>
      <a href="#notification" data-toggle="tab">Notifications</a>
    </li>
    <li>
      <a href="#sequrity" data-toggle="tab">Sequrity</a>
    </li>

  </ul>
  <br>
  <div class="tab-content">
    <div class="tab-pane active" id="common">


      <div class="row">
        <div class="col-xs-12 col-sm-9 col-md-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-1">
          <%= form_for @user, :url => update_userinfo_user_path(@user) do |f| %>
            <dl class="dl-horizontal">

              <div class="form-group">
                <dt><%= f.label :name, "Name" %></dt>
                <dd><%= f.text_field :name, class: "form-control" %></dd>
              </div>

              <div class="form-group">
                    <dt><%= f.label :lastname, "Lastname" %></dt>
                    <dd><%= f.text_field :lastname, class: "form-control" %></dd>
              </div>

              <div class="form-group">
                    <dt><%= f.label :gender_id, "Gender" %></dt>
                    <dd><%= f.collection_select :gender_id, Gender.order(:id),
                                                :id, :gendername, {}, {class: "form-control"} %></dd>
              </div>

              <div class="form-group">
                <dt><%= f.label :relationship_id, "Relationship" %></dt>
                <dd><%= f.collection_select :relationship_id, Relationship.order(:id),
                                            :id, :relationshipname, {}, {class: "form-control"} %></dd>
              </div>

              <div class="form-group">
                <dt><%= f.label :birthdate, "Birthdate" %></dt>
                <dd><%= f.date_select :birthdate, placeholder: "YYYY-MM-DD", class: "form-control" %></dd>
              </div>

              <div class="form-group">
                <dt><%= f.label :countru_id, "Country" %></dt>

                <dd><%= f.collection_select :country_id, Country.order(:id),
                                            :id, :countryname, {}, {class: "form-control"} %></dd>

              </div>

              <div class="form-group">
                <%= f.fields_for :city do |city| %>
                    <dt><%= city.label :cityname, "City" %></dt>
                    <dd><%= city.text_field :cityname, class: "form-control" %></dd>
                <% end %>
              </div>

              <dd><%= f.submit "Save", class: "btn btn-primary center" %></dd>

          <% end %>
          </dl>
        </div>
      </div>




    </div>
    <div class="tab-pane" id="languages">

      <hr>


    </div>
    <div class="tab-pane" id="interests">
      <div class="row">
        <div class="col-xs-12 col-sm-9 col-md-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-1">
          <%= form_for @user, :url => update_name_user_path(@user) do |f| %>
              <dl class="dl-horizontal">
                <div class="form-group">
                  <dt><%= f.label :login, "Activities" %></dt>
                  <dd><%= f.text_area :login, :class => "form-control" %></dd>
                </div>

                <div class="form-group">
                  <dt><%= f.label :login, "Interests" %></dt>
                  <dd><%= f.text_area :login, :class => "form-control" %></dd>
                </div>

                <div class="form-group">
                  <dt><%= f.label :login, "Favorite music" %></dt>
                  <dd><%= f.text_area :login, :class => "form-control" %></dd>
                </div>

                <div class="form-group">
                  <dt><%= f.label :login, "Favorite movies" %></dt>
                  <dd><%= f.text_area :login, :class => "form-control" %></dd>
                </div>

                <div class="form-group">
                  <dt><%= f.label :login, "Favorite books" %></dt>
                  <dd><%= f.text_area :login, :class => "form-control" %></dd>
                </div>

                <div class="form-group">
                  <dt><%= f.label :login, "Favorite games" %></dt>
                  <dd><%= f.text_area :login, :class => "form-control" %></dd>
                </div>

                <div class="form-group">
                  <dt><%= f.label :login, "Favorite quotes" %></dt>
                  <dd><%= f.text_area :login, :class => "form-control" %></dd>
                </div>

                <div class="form-group">
                  <dt><%= f.label :login, "About me" %></dt>
                  <dd><%= f.text_area :login, :class => "form-control" %></dd>
                </div>

                <dd><%= f.submit "Save", class: "btn btn-primary center" %></dd>

          <% end %>
          </dl>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
    <%= render 'layouts/users_search_panel' %>


  <div class="row">
    <% @users.each do |u| %>

        <%= render 'layouts/user_tile', :user => u %>

    <% end %>

  </div>

    <%= will_paginate @users %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>

<div class="text-center">
  <h1>Sign Up</h1>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for @user do |f| %>
        <%= render 'shared/error_messages' %>

        <div class="form-group">
            <%= f.label :name, "Name" %>
            <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :lastname, "Lastname" %>
            <%= f.text_field :lastname, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.fields_for :gender do |u| %>
              <%= u.label :gender_id, "Gender" %>
              <%= u.collection_select :gender_id, Gender.order(:id),
                                          :id, :gendername, {}, {class: "form-control"} %>
          <% end %>
        </div>

        <div class="form-group">
            <%= f.label :email, "Email" %>
            <%= f.text_field :email, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.file_field :avatar %>
        </div>

        <div class="form-group">
            <%= f.label :password, "Password" %>
            <%= f.password_field :password, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'User') %>

<!-- <div class="well">
  <p>О чем ты сейчас думаешь?</p>
</div> -->

<div class="row" xmlns="http://www.w3.org/1999/html">
  <div class="col-xs-5 col-sm-5 col-md-4">
    <%= image_tag(@user.avatar.url(:medium), class: "img-rounded img-responsive") %>

    <br><br>

    <div class="list-group">

    <% if @user == current_user %>

          <p>Fotos with me</p>
          <p>Posts with me</p>

          <h4 class="heading-xs">Profile is filled on: <span class="pull-right">64%</span></h4>
          <div class="progress progress-u progress-xxs margin-bottom-40">
            <div style="width: 64%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="64" role="progressbar" class="progress-bar progress-bar-dark">
            </div>
          </div>
          <p>Add contact info</p>
          <p>Add info about education</p>
          <p>Add your hobbies</p>


    <% else %>


          <% if friends?(@user) %>
            <p class="list-group-item">Friends</p>
          <% elsif friends_request_sent?(@user) %>
            <p class="list-group-item">Friend request sent</p>
          <% elsif friends_request_received?(@user) %>
              <%= link_to add_friend_path(:friend_id => @user.id), class: "list-group-item" do %>
                  Accept friend
              <% end %>
              <%= link_to '#', class: "list-group-item" do %>
                  Decline
              <% end %>
          <% else %>
              <%= link_to add_friend_path(:friend_id => @user.id), class: "list-group-item" do %>
                  Send friend request
              <% end %>
          <% end %>


      <%= link_to new_user_conversation_path(@user), class: "list-group-item" do %>
          Send Message
      <% end %>

          <% end %>


    </div>
  </div>

  <div class="col-xs-6 col-sm-6 col-md-7">
    <h4>
      <%= @user.name %> <%= @user.lastname %>
    </h4>
  </div>
  <div class="col-xs-1 col-sm-1 col-md-1">
    <%= link_to "", edit_user_path(@user), class: "pull-right btn glyphicon glyphicon-pencil" %>
  </div>
  <div class="col-md-8">
    <hr>
    <p>Country: <%= @user.country.countryname %></p>
    <p>City:<%= @user.city.cityname %></p>
    <p>Gender: <%= @user.gender.gendername %></p>
    <p>Relationship: <%= @user.relationship.relationshipname %></p>

    <p>Speaks: English, French</p>
    <p>Learning: Russian, Spanish</p>
    <p>Looking for: Language exchange <br> Friendship <br> Voyages</p>

    <p>Joined 2 months ago</p>
  </div>
</div>

<%= form_for [@user, Post.new] do |f| %>



  <div class="row">
    <div class="col-sm-12">
      <%= f.text_area :text, class: "form-control", :rows => "3", :placeholder => "Write a message..." %>
      <%= f.hidden_field :author_id, :value => current_user.id %>
      </br>
      <%= f.submit "Post", class: "btn btn-primary pull-right" %>
      <a data-placement="top" class="btn btn-success btn-xs glyphicon glyphicon-user" href="#" title="Add user"></a>
      <a data-placement="top" class="btn btn-success btn-xs glyphicon glyphicon-picture" href="#" title="Add image"></a>
      <a data-placement="top" class="btn btn-success btn-xs glyphicon glyphicon-map-marker" href="#" title="Add place"></a>

    </div>
  </div>

<% end %>

<br>

<div class="row">

<% @user.posts.reverse.each do |p| %>

  <div class="col-md-12 row">
    <div class="col-xs-3 col-sm-3 col-md-2">
      <%= image_tag( p.author.avatar.url(:small), class: "img-rounded img-responsive") %>

      <br>

    </div>
    <div class="col-xs-9 col-sm-9 col-md-10">
      <strong class="primary-font"><%= link_to "#{p.author.name}", p.author %></strong>

      <small class="pull-right text-muted">
        <span class="glyphicon glyphicon-time"></span> <%= time_ago_in_words(p.created_at) %> ago
      </small>


      <p><%= p.text %></p>
    </div>
  </div>


<% end %>





</div>

app/views/users/temp.html.erb
This is for Index.html.erb - the list of users in the system


<div class="col-md-4">
  <div class="col-md-6">
    <%= image_tag( user.avatar.url(:small), class: "img-rounded") %> <br><br>

    <p>
      <%= link_to add_friend_path(:friend_id => user.id),
                  class: "btn btn-success btn-xs #{"disabled btn-info" if friends_request_sent?(user) }" do %>

          <% if friends?(user) %>
              Friends
              <span class="glyphicon glyphicon-user"></span>
          <% elsif friends_request_received?(user) %>
              <%= link_to 'Accept', add_friend_path(:friend_id => user.id), class: "btn btn-success btn-xs" %>
              <%= link_to 'Decline', '#', class: "btn btn-danger btn-xs" %>

          <% elsif friends_request_sent?(user) %>
              Requested
              <span class="glyphicon glyphicon-ok"></span>
          <% else %>
              Add friend
              <span class="glyphicon glyphicon-plus"></span>
          <% end %>

          <%= link_to 'Delete', unfriend_path(:id => user.id ), :method => :delete %> <br>


      <% end %>
      <br><br>
    </p>

  </div>
  <div class="col-md-6">
    <h4><%= link_to "#{user.name}", user %></h4>
    <a href="#" class="btn btn-xs btn-default"><span class="glyphicon glyphicon-comment"></span> Message</a>

  </div>
</div>



#Friends list

    <h1>Your friends</h1>

    <% @friends.each do |friend| %>

        <%= friend.name %> | <%= link_to 'Delete from friends', unfriend_path(:id => friend.id ), :method => :delete %> <br>

    <% end %>


    <h1>Sent friendship requests to</h1>

    <% @friend_requests_sent.each do |friend| %>

        <%= friend.id %> <%= friend.name %> | <%= link_to 'Delete', unfriend_path(:id => friend.id ), :method => :delete %> <br>

    <% end %>

    <h1>Recieved friendship requests from</h1>

    <% @friend_requests_received.each do |friend| %>

        <%= friend.id %> <%= friend.name %> <%= link_to 'Accept', add_friend_path(:friend_id => friend.id) %> <br>

    <% end %>





<div class="form-group">
  <%= f.fields_for :gender do |u| %>
      <dt><%= u.label :gender_id, "Gender" %></dt>
      <dd><%= u.collection_select :gender_id, Gender.order(:id),
                                  :id, :gendername, {}, {class: "form-control"} %></dd>
  <% end %>
</div>

<div class="form-group">
  <dt><%= f.label :relationship_id, "Relationship" %></dt>
  <dd><%= f.collection_select :relationship_id, Relationship.order(:id),
                              :id, :relationshipname, {}, {class: "form-control"} %></dd>
</div>

<div class="form-group">
  <%= f.fields_for :userinfo do |u| %>
      <dt><%= u.label :birthday, "Birthday" %></dt>
      <dd><%= u.date_select :birthday, {:start_year => Time.now.year - 100}, {class: "form-control"} %></dd>
  <% end %>
</div>

<div class="form-group">
  <dt><%= f.label :countru_id, "Country" %></dt>

  <dd><%= f.collection_select :country_id, Country.order(:id),
                              :id, :countryname, {}, {class: "form-control"} %></dd>

</div>

<div class="form-group">
  <%= f.fields_for :city do |city| %>
      <dt><%= city.label :cityname, "City" %></dt>
      <dd><%= city.text_field :cityname, class: "form-control" %></dd>
  <% end %>
</div>