config/routes.rb
Rails.application.routes.draw do

  get 'settings/index'

  match '/signup',                to: 'users#new',            via: 'get'
  match '/signin',                to: 'sessions#new',         via: 'get'
  match '/signout',               to: 'sessions#destroy',     via: 'delete'

  match '/help',                  to: 'static_pages#help',    via: 'get'

  match '/users',                 to: 'users#index',          via: 'get'
  match '/about',                 to: 'static_pages#about',   via: 'get'

  match '/friends',               to: 'friendships#index',    via: 'get'
  match '/add_friend',            to: 'friendships#create',   via: 'get'
  match '/unfriend',              to: 'friendships#destroy',  via: 'delete'

   root 'static_pages#index'

  resources :users do
    member do
      patch :update_name
      patch :update_userinfo
    end
    resources :posts
    resources :conversations do
      resources :messages
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright © Smirnov Konstantin, <%= Time.now.year %>
  </small>
  <nav>
    <ul>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><a href="http://justforeignblog.tumblr.com/">Our Blog</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<br>

<nav role="navigation" class="navbar navbar-default">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'JUSTFOREIGN', root_path, class: "navbar-brand" %>
  </div>
  <!-- Collection of nav links and other content for toggling -->
  <div id="navbarCollapse" class="collapse navbar-collapse">

    <ul class="nav navbar-nav">

    </ul>

    <ul class="nav navbar-nav navbar-right">

      <% if signed_in? %>

      <li class="<%= 'active' if params[:controller] == 'users' && params[:action] == 'index' %>">
        <%= link_to 'People', users_path %>
      </li>

      <li><a href="#">Groups</a></li>
          <li><a href="#">Chats</a></li>
          <li class="<%= 'active' if params[:controller] == 'static_pages' && params[:action] == 'help' %>"><%= link_to 'Help', help_path %></li>
      <li><%= link_to 'Log out', signout_path, method: :delete %></li>



    <% else %>

      <li><a href="#">Help</a></li>
      <li><%= link_to 'Log in', signin_path %></li>

      <% end %>

    </ul>


  </div>
</nav>

app/views/layouts/_left_menu.html.erb
    <div class="list-group">
      <%= link_to current_user, class: "list-group-item #{ "active" if params[:controller] == 'users' && @user == current_user && params[:action] =='show' }" do %>
          My Profile
      <% end %>

      <%= link_to friends_path, class: "list-group-item #{ "active" if params[:controller] == 'friendships' && params[:action] == 'index' }" do %>
            My Friends
          <% if friend_requests_received_quantity > 0 %>
            <span class="badge alert-info"><%= friend_requests_received_quantity %></span>
          <% end %>
      <% end %>

      <%= link_to "#", class: "list-group-item" do %>
        My messages
      <% end %>


      <%= link_to "#", class: "list-group-item" do %>
        My fotos
      <% end %>

      <%= link_to "#", class: "list-group-item" do %>
        My groups
      <% end %>

      <%= link_to "#", class: "list-group-item" do %>
        My events
      <% end %>


      <%= link_to root_path, class: "list-group-item #{ "active" if params[:controller] == 'static_pages' && params[:action] == 'index'}" do %>
          My news
      <% end %>

      <%= link_to edit_user_path(@current_user), class: "list-group-item #{ "active" if params[:controller] == 'users' && (params[:action] == 'edit' or params[:action] == 'update_userinfo')}" do %>
        Settings
      <% end %>

    </div>


    <div class="list-group">
      <a href="#" class="list-group-item clearfix">
        <span class="glyphicon glyphicon-paperclip"></span>
        Nullam quis risus eget urna mollis ornare vel eu leo.
        Vestibulum id ligula porta felis euismod semper.
        Cras mattis consectetur purus sit amet fermentum.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    <span class="pull-right">
      <button class="btn btn-xs btn-info">CCS</button>
      <button class="btn btn-xs btn-warning">
        <span class="glyphicon glyphicon-trash"></span>
      </button>
    </span>
      </a>
    </div>

app/views/layouts/_post.html.erb
<div class="row" xmlns="http://www.w3.org/1999/html">

  <hr>

  <div class="">
    <div class="col-md-2 pull-left image">
      <img src="http://bootdey.com/img/Content/user_3.jpg" class="img-responsive  img-circle">
    </div>
    <div class="col-md-10">
      <div class="title h5">
        <a href="#"><b>Ryan Haywood</b></a>
        made a post.
      </div>
      <h6 class="text-muted time">1 minute ago</h6>

    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium</p>

      <a data-placement="top" class="btn btn-success btn-xs glyphicon glyphicon-ok tip" href="#" title="View"></a>
      <a data-placement="top" class="btn btn-danger  btn-xs glyphicon glyphicon-trash tip" href="#" title="Delete"></a>
      <a data-placement="top" class="btn btn-info  btn-xs glyphicon glyphicon-share tip" href="#" title="Share"></a>
      <a data-placement="top" class="btn btn-info btn-xs glyphicon glyphicon-heart pull-right" href="#" title="Like"></a>

    </div>
  </div>

  </div>


<br>

  <div class=" post">


    <div class="post-footer">
      <div class="input-group">
        <input class="form-control" placeholder="Add a comment" type="text">
                    <span class="input-group-addon">
                        <a href="#"><i class="glyphicon glyphicon-pencil"></i></a>
                    </span>
      </div>

      <ul class="comments-list">

        <li class="comment">
          <a class="pull-left" href="#">
            <img class="avatar" src="http://bootdey.com/img/Content/user_1.jpg" alt="avatar">
          </a>
          <div class="comment-body">
            <div class="comment-heading">
              <h4 class="user">Gavino Free</h4>
              <h5 class="time">5 minutes ago</h5>
            </div>
            <p>Sure, oooooooooooooooohhhhhhhhhhhhhhhh</p>
          </div>
        </li>

        <li class="comment">
          <a class="pull-left" href="#">
            <img class="avatar" src="http://bootdey.com/img/Content/user_1.jpg" alt="avatar">
          </a>
          <div class="comment-body">
            <div class="comment-heading">
              <h4 class="user">Gavino Free</h4>
              <h5 class="time">5 minutes ago</h5>
            </div>
            <p>Sure, oooooooooooooooohhhhhhhhhhhhhhhh</p>
          </div>
        </li>


      </ul>
    </div>

  </div>

app/views/layouts/_user_tile.html.erb
<div class="col-md-6 row">
  <div class="col-xs-3 col-sm-3 col-md-4">
    <%= image_tag( user.avatar.url(:small), class: "img-rounded img-responsive") %>

    <div class="btn-group btn-group-justified" role="group">

      <% if friends?(user) %>

          <%= link_to unfriend_path(:id => user.id), :method => :delete, class: "btn btn-primary btn-xs" do %>
              Friends <span class="glyphicon glyphicon-user"></span>
          <% end %>

      <% elsif friends_request_received?(user) %>

          <%= link_to add_friend_path(:friend_id => user.id), class: "btn btn-success btn-xs" do %>
              <span class="glyphicon glyphicon-ok"></span>
          <% end %>

          <%= link_to '#decline', class: "btn btn-danger btn-xs" do %>
              <span class="glyphicon glyphicon-remove"></span>
          <% end %>

      <% elsif friends_request_sent?(user) %>

          <%= link_to unfriend_path(:id => user.id), :method => :delete, class: "btn btn-info btn-xs" do %>
             Waiting <span class="glyphicon glyphicon-time"></span>
          <% end %>

      <% else %>

          <%= link_to add_friend_path(:friend_id => user.id), class: "btn btn-success btn-xs" do %>
              Add <span class="glyphicon glyphicon-plus"></span>
          <% end %>

      <% end %>


    </div>

    <br>

  </div>
  <div class="col-xs-8">
    <h4><%= link_to "#{user.name} #{user.lastname}", user %></h4>
    <p>Moscow, 25 years</p>
    <p><i>There is my quotation, or my status</i></p>

  </div>
</div>

app/views/layouts/_users_search_panel.html.erb
<div class="well">
  There is a search panel to find a user by his country, age etc
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- BOOTSTRAP CDN -->
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>


<div class="container">
  <%= render 'layouts/header' %>

    <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %>
          </div>
    <% end %>

  <% if signed_in? %>

  <div class="row">
    <div class="col-sm-3 sidebar">
      <%= render 'layouts/left_menu' %>
    </div>
    <div class="col-sm-9">
      <%= yield %>
    </div>
  </div>

      <% else %>

      <%= yield %>

      <% end %>

  <%= render 'layouts/footer' %>

  <%= debug(params) if Rails.env.development? %>
</div>



</body>
</html>